# Smoobu API configuration
SMOOBU_SETTINGS_CHANNEL_ID = '1115695'
SMOOBU_API_KEY = '9V1lV6cSqy8EbeOV1v4cXIIuIgNl41Pz'

# Babel configuration
BABEL_DEFAULT_LOCALE = 'en'
BABEL_DEFAULT_TIMEZONE = 'UTC'
